security:
    encoders:
        AW\DoliBundle\Entity\User:
            algorithm: md5
            encode_as_base64: false
            iterations: 0

    providers:
        main:
            # Custom provider engendre de gros lenteur pour certains utilisateurs internes
            #id: aw.doli.security.user_provider
            entity:
                class: AW\DoliBundle\Entity\User
                property: login

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
        ROLE_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|libs)/
            security: false

        login:
            pattern: /login$
            anonymous: true

        main:
            pattern: ^/
            anonymous: false
            form_login:
                provider: main
                csrf_token_generator: security.csrf.token_manager
                success_handler: aw.doli.event_listener.useraccess_listener
            logout: true
            remember_me:
                secret: '%secret%'
                lifetime: 36000 # 10 heures
                path: /
            switch_user: true
