<?php

namespace AW\PlansBundle\Repository;

/**
 * ConsigneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsigneRepository extends \Doctrine\ORM\EntityRepository
{
}
