<?php

namespace AW\PlansBundle\Repository;

/**
 * TypeBatimentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeBatimentRepository extends \Doctrine\ORM\EntityRepository
{
}
