<?php

namespace AW\DoliBundle\Repository;

/**
 * CategoryExtrafieldsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryExtrafieldsRepository extends \Doctrine\ORM\EntityRepository
{
}
