<?php

namespace AW\DoliBundle\Repository;

/**
 * CommandeDetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeDetRepository extends \Doctrine\ORM\EntityRepository
{
}
