<?php

namespace AW\DoliBundle\Repository;

/**
 * CommandeFactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeFactureRepository extends \Doctrine\ORM\EntityRepository
{
}
