<?php

namespace AW\DoliBundle\Repository;

/**
 * CommandeExtrafieldsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeExtrafieldsRepository extends \Doctrine\ORM\EntityRepository
{
}
