<?php

namespace AW\DoliBundle\Repository;

/**
 * ContactExtrafieldsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactExtrafieldsRepository extends \Doctrine\ORM\EntityRepository
{
}
