<?php

namespace AW\DoliBundle\Repository;

/**
 * ContactLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
