<?php

namespace AW\DoliBundle\Repository;

/**
 * FactureExtrafieldsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureExtrafieldsRepository extends \Doctrine\ORM\EntityRepository
{
}
