<?php

namespace AW\DoliBundle\Repository;

/**
 * PaiementFactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaiementFactureRepository extends \Doctrine\ORM\EntityRepository
{
}
