<?php

namespace AW\DoliBundle\Repository;

/**
 * ProductExtrafieldsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductExtrafieldsRepository extends \Doctrine\ORM\EntityRepository
{
}
