<?php

namespace AW\DoliBundle\Repository;

/**
 * RightsDefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RightsDefRepository extends \Doctrine\ORM\EntityRepository
{
}
