<?php

namespace AW\DoliBundle\Repository;

/**
 * SocieteInfosPlansRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocieteInfosPlansRepository extends \Doctrine\ORM\EntityRepository
{
}
