<?php

namespace AW\DoliBundle\Repository;

/**
 * UsergroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsergroupRepository extends \Doctrine\ORM\EntityRepository
{
}
